/**
 * Built-in question decks. Keyed by the deck `id` defined in `constants/decks.ts`.
 *
 * Content for Deep Spill, No Dead Air, Chaos Mode, Hot Seat and Date Mode is
 * transcribed from `prompt/built-in-questions.md`. The Drop Lore set is authored
 * to match the deck's storytelling / lore-dropping vibe.
 *
 * Screens are length-agnostic: the in-game progress counter ("n of total") and
 * the progress dots derive from each list's length, so decks can have any count.
 */
export const QUESTIONS: Record<string, string[]> = {
  "deep-spill": [
    "What's something you wish people understood about you?",
    "What's one thing you're still learning to accept about yourself?",
    "When was the last time you felt genuinely proud of yourself?",
    "What's a fear you don't talk about often?",
    "What's one mistake that taught you a lot?",
    "What kind of person do you want to become?",
    "What's something you miss from your younger self?",
    "What's one thing you're trying to heal from?",
    "What makes you feel safe around someone?",
    "What's a lesson you learned the hard way?",
    "What's something you pretend doesn't bother you?",
    "What do you usually overthink about?",
    "What's one thing you're grateful for right now?",
    "What's something you want to be remembered for?",
    "When do you feel most like yourself?",
    "What's a boundary you're trying to protect?",
    "What's something you wish you had said earlier?",
    "What does peace look like for you?",
    "What's one thing you're afraid to fail at?",
    "What kind of love or friendship feels healthy to you?",
  ],
  "no-dead-air": [
    "What's your go-to comfort food?",
    "What song have you been replaying lately?",
    "What's your most used emoji?",
    "What app do you open way too much?",
    "What's your favorite lazy-day activity?",
    "What's your usual drink order?",
    "What movie or series can you rewatch anytime?",
    "What's something small that instantly improves your mood?",
    "What's your go-to snack?",
    "What's your favorite time of the day?",
    "What's one random thing you're good at?",
    "What's your ideal weekend plan?",
    "What's a food you'll never get tired of?",
    "What's your current favorite meme or trend?",
    "What's your favorite way to relax?",
    "What's one thing you always forget?",
    "What's the last thing that made you laugh?",
    "What's your favorite weather?",
    "What's one item you always bring with you?",
    "What's your go-to excuse when you're late?",
  ],
  "drop-lore": [
    "What's a story from your past that explains a lot about you?",
    "What's the origin story behind one of your nicknames?",
    "What's a childhood moment you still think about?",
    "What's the lore behind your oldest friendship?",
    "What's a wildly specific memory that lives in your head rent-free?",
    "What's the most chaotic thing that happened on a family trip?",
    "What's a phase you went through that you'll never live down?",
    "What's the backstory to your biggest fear?",
    "What's a small decision that completely changed your timeline?",
    "What's the most legendary thing you did in school?",
    "What's a secret talent and how did you discover it?",
    "What's the story of the worst haircut you ever had?",
    "What's a time you accidentally became the main character?",
    "What's the most embarrassing crush story you'll admit to?",
    "What's a tradition only your family or friend group understands?",
    "What's the wildest coincidence that's ever happened to you?",
    "What's a moment you realized you'd grown up?",
    "What's the story behind your most prized possession?",
    "What's an inside joke and how was it born?",
    "What's the lore drop people would be surprised to learn about you?",
  ],
  "chaos-mode": [
    "What's your most unserious fear?",
    "What's your villain origin story?",
    "What's your most delulu belief?",
    "What's a hill you would die on, even if it's dumb?",
    "What's your most NPC habit?",
    "What's something you hate for no clear reason?",
    "What's your most chaotic online purchase?",
    "What's your toxic trait, but make it funny?",
    "What's your \"I'm cooked\" moment this week?",
    "What's the weirdest thing you searched that was harmless?",
    "What's something normal that feels illegal to do?",
    "What's your most random ick?",
    "What's a dramatic reaction you had to a minor problem?",
    "What food would you defend with your life?",
    "What's something you do that deserves a side-eye?",
    "What's your most useless talent?",
    "What's the dumbest thing that made you laugh recently?",
    "What's your most chaotic group chat moment?",
    "What's something you would cancel plans for immediately?",
    "What's one thing that gives you instant main character energy?",
  ],
  "hot-seat": [
    "Who in this group is the most dramatic?",
    "Who is most likely to be late?",
    "Who gives the best advice here?",
    "Who is most likely to overthink a simple message?",
    "Who has the funniest reactions?",
    "Who is the most difficult to read?",
    "Who is most likely to disappear and come back like nothing happened?",
    "Who in this group has the most chaotic energy?",
    "Who is most likely to start laughing at the wrong time?",
    "Who would survive best in a random emergency?",
    "Who is the most honest in the group?",
    "Who gives off main character energy?",
    "Who is most likely to accidentally expose a secret?",
    "Who takes the longest to reply?",
    "Who is the most protective friend?",
    "Who is most likely to say \"I'm fine\" but is not fine?",
    "Who would be the worst at keeping a straight face?",
    "Who is most likely to make a bad decision for the plot?",
    "Who has changed the most over time?",
    "Who in this group knows the most tea?",
  ],
  "date-mode": [
    "What's your ideal first date?",
    "What makes you feel comfortable with someone?",
    "What's a green flag you notice quickly?",
    "What's a red flag you never ignore?",
    "What's your love language?",
    "What kind of effort matters most to you?",
    "What's something small that makes you feel appreciated?",
    "What's your idea of quality time?",
    "What's a romantic gesture you actually like?",
    "What's something you value in a relationship?",
    "What's your favorite way to show affection?",
    "What makes you lose interest quickly?",
    "What's something you want a partner to understand about you?",
    "What's your dating non-negotiable?",
    "What's the best compliment someone can give you?",
    "What kind of communication do you prefer?",
    "What's something that instantly makes someone attractive to you?",
    "What's a simple date idea you would genuinely enjoy?",
    "What's something you're still learning about relationships?",
    "What does a healthy relationship look like to you?",
  ],
};

/** Questions for a deck, or an empty array for an unknown id. */
export function getQuestionsForDeck(deckId: string | undefined): string[] {
  return (deckId && QUESTIONS[deckId]) || [];
}
